### ISSUE TITLE
Unable to run the app

### ISSUE THREAD

**Issue by cretaes** [drowsy-coder/femunity#11]
`flutter run`

return me the following message:

```
Resolving dependencies... (3.9s)
The current Dart SDK version is 3.0.1.

Because flutter_animations 0.0.1+10 doesn't support null safety and no versions of flutter_animations match >0.0.1+10 <0.1.0, flutter_animations ^0.0.1+10 is forbidden.
So, because femunity depends on flutter_animations ^0.0.1+10, version solving failed.

The lower bound of "sdk: '>=2.7.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.
For details, see https://dart.dev/null-safety

```

Any idea to solve this?

Thank you for your effort on this project.

Regards,
Stefano

**Comment by drowsy-coder** [comment]
Hey Stefano,

Looks like you are running Dart SDK 3.0.1, but the application has been developed with Dart SDK 2.19. You could either try removing the flutter_animations package from the pubspec.yaml file or you could downgrade your SDK.

Also I suggest you to use your own Firebase setup as you wouldn't be able to access my app due to SHA key mismatch.

For using the app, you could download the APK from the releases section, do note that the app and the content inside are in testing as we closed the first public beta last month. Let me know if you have any other queries.

Best,
Amritansh

**Comment by cretaes** [comment]
Hi Amritansh,

I hope this message finds you well.

Thank you so much for your detailed guidance regarding the Dart SDK version and the flutter_animations package. Your expertise and knowledge are indeed commendable.

Your advice on the Firebase setup was very insightful. I appreciate you taking the time to explain this to me. It's clear to see the depth of your understanding and dedication you've put into this open source project.

The work you have done, and continue to do, on this project is exceptional. It's impressive to see how far the project has come, especially with the successful closure of the first public beta last month.

I will definitely take all of your recommendations into account as I continue working with the application. I will also look forward to checking out the APK in the releases section.

I am sure I will be reaching out to you again soon for more insights and expertise. Until then, keep up the fantastic work.

Best regards,
Stefano
